Repository WildCodeSchool-CDA-FT-2025-03/projet1_fantastic_4, pull requests merged in 2025-04, with the labels that each got.

#92 feat(047-task): migrate categories done
  server/package.json
  server/src/services/datas.service.ts
  server/src/services/migration/categories.json
  server/src/services/migration/migrate.ts
Labels: Change requested

#95 Feature/043 us/seed/movies
  server/src/entities/categories.entity.ts
  server/src/entities/movie.entity.ts
  server/src/main.ts
  server/src/resolvers/movies.resolver.ts
  server/src/services/datas.service.ts
  server/src/services/migration/migrate.ts
  server/src/services/migration/movies.json
  server/src/services/migration/movies.migrate.ts
Labels: Change requested, Lead Review

#96 Feature/020 us/back game info
  server/src/entities/games/categories.entity.ts
  server/src/entities/games/companies.entity.ts
  server/src/entities/games/games.entity.ts
  server/src/entities/games/languages.entity.ts
  server/src/entities/games/pegiesbr.entity.ts
  server/src/entities/games/tags.entity.ts
  server/src/main.ts
  server/src/resolvers/games.resolver.ts
  server/src/services/datas.service.ts
  server/src/services/migration/games.json
  server/src/services/migration/games.migrate.ts
  server/src/services/migration/migrate.ts
Labels: Lead Review

#94 Feature/001 us/navbar
  client/src/App.tsx
  client/src/components/Header/Burgermenu/Burgermenu.css
  client/src/components/Header/Burgermenu/Burgermenu.tsx
  client/src/components/Header/Header.css
  client/src/components/Header/Header.tsx
  client/src/components/Header/Navbar/Navbar.css
  client/src/components/Header/Navbar/Navbar.tsx
  client/src/global.css
Labels: Change requested, Lead Review

#98 Feature/043 us/new in movies carousel
  client/.gitignore
  client/src/components/Carousel/Carousel.tsx
  client/src/pages/movies/MoviesPage.tsx
  client/src/schemas/movie.schema.ts
  client/src/utiles/fakeDatasCarousel.json
  server/src/resolvers/movies.resolver.ts
  server/src/services/migration/categories.json
Labels: Change requested, Lead Review

#101 Feature/020 us/games link front back
  client/src/pages/games/GameInfo/GameInfo.tsx
  client/src/schemas/games.schema.ts
  client/src/services/client-apollo.service.ts
  client/src/types/game.type.ts
Labels: Lead Review

#97 feat(044-feat): music page + musicdata
  client/src/components/Panel/MediaPanel.tsx
  client/src/components/Panel/mediaPanel.css
  client/src/global.css
  client/src/pages/musics/MusicsPage.css
  client/src/pages/musics/MusicsPage.tsx
  client/src/utiles/musics.json
Labels: Change requested, Lead Review

#102 Feature/044 us/music entity resolver
  client/src/pages/musics/MusicsPage.tsx
  server/package.json
  server/src/entities/musics.entity.ts
  server/src/main.ts
  server/src/resolvers/musics.resolver.ts
  server/src/services/datas.service.ts
  server/src/services/migration/migrate.ts
  server/src/services/migration/musics/musicMigrate.ts
  server/src/services/migration/musics/musics.json
Labels: Conflit détecté

#100 Feature/001 us/header
  client/public/burgerMenu.svg
  client/public/close.svg
  client/src/components/Header/Header.css
  client/src/components/Header/Header.tsx
  client/src/components/Header/Navbar/Navbar.css
  client/src/components/Header/Navbar/Navbar.tsx
  client/src/global.css
  client/src/schemas/categories.schema.ts
Labels: Change requested, Lead Review

#103 Feature/043 us/recommandations movies carousel
  client/src/components/Carousel/Carousel.tsx
  client/src/components/CarouselNewInMovies.tsx
  client/src/components/CarouselRecoMovies.tsx
  client/src/pages/movies/MoviesPage.tsx
  client/src/schemas/movie.schema.ts
  server/src/entities/movie.entity.ts
  server/src/resolvers/movies.resolver.ts
  server/src/services/migration/movies.migrate.ts
  server/src/utils/shuffleArray.ts
Labels: Conflict Resolved, Conflit détecté

#105 feat(057-us): add parameter, limit, page, order and dir for getGame
  server/src/resolvers/games.resolver.ts
Labels: Lead Review

#107 feat(044-feat): get music data from graphql
  client/src/pages/musics/MusicsPage.css
  client/src/pages/musics/MusicsPage.tsx
  client/src/schemas/musics.schema.ts
  server/src/entities/categories.entity.ts
  server/src/entities/musics.entity.ts
  server/src/resolvers/musics.resolver.ts
  server/src/services/migration/musics/musicMigrate.ts
  server/src/services/migration/musics/musics.json
Labels: Change requested

#106 Feature/042 us/booksentities v2
  server/src/entities/books.entity.ts
  server/src/main.ts
  server/src/resolvers/books.resolver.ts
  server/src/services/datas.service.ts
  server/src/services/migration/books.json
  server/src/services/migration/books.migration.ts
  server/src/services/migration/migrate.ts
Labels: Lead Review

#109 Feature/057 us/client home game
  client/src/components/Carousel/CardMedia.css
  client/src/components/Carousel/CardMedia.tsx
  client/src/components/Carousel/Carousel.tsx
  client/src/components/CarouselNewInGame.tsx
  client/src/components/CarouselRecoGame.tsx
  client/src/pages/games/GamesPage.css
  client/src/pages/games/GamesPage.tsx
  client/src/schemas/games.schema.ts
Labels: Lead Review

#112 Feature/042 us/bookscomponents
  client/src/components/CarouselNewInBooks.tsx
  client/src/components/CarouselRecoBooks.tsx
  client/src/pages/books/BooksPage.tsx
  client/src/schemas/books.schema.ts
  server/src/entities/books.entity.ts
  server/src/entities/categories.entity.ts
  server/src/resolvers/books.resolver.ts
Labels: Lead Review

#118 Feature/013 us/one movie page
  client/src/components/MediaInfoLayout/MediaInfoLayout.tsx
  client/src/pages/movies/MovieInfo/MovieInfo.tsx
  client/src/routers/routers.tsx
  client/src/schemas/movie.schema.ts
  server/src/entities/movie.entity.ts
  server/src/resolvers/movies.resolver.ts
  server/src/services/migration/movies.migrate.ts
Labels: Change requested, Conflict Resolved

#120 Feature/026 us/switch theme
  client/src/App.tsx
  client/src/components/Carousel/CardMedia.css
  client/src/components/Header/Header.css
  client/src/components/Header/Header.tsx
  client/src/components/Header/Navbar/Navbar.css
  client/src/components/Header/Navbar/ThemeButton.tsx
  client/src/components/Header/Navbar/themeButton.css
  client/src/components/MediaInfoLayout/MediaInfoLayout.css
  client/src/components/Panel/mediaPanel.css
  client/src/contexts/themeProvider.tsx
  client/src/global.css
  client/src/main.tsx
  client/src/types/themeContext.type.ts
  client/src/utiles/useTheme.tsx
Labels: Change requested, Correction faite

#124 Feature/072 us/style adjustement
  client/src/components/Carousel/CardMedia.css
  client/src/components/Carousel/Skeleton.css
  client/src/components/Header/Header.tsx
  client/src/components/MediaInfoLayout/MediaInfoLayout.css
  client/src/components/MediaInfoLayout/SimpleExtraInfo/SimpleExtraInfos.css
  client/src/components/MediaInfoLayout/WordList/WordList.css
  client/src/global.css
  client/src/pages/movies/MoviesPage.css
Labels: Lead Review, Reviewed

#125 Feature/071 us/bookinfo
  client/src/components/Carousel/CardMedia.css
  client/src/components/Carousel/Skeleton.css
  client/src/global.css
  client/src/pages/books/Bookinfo/Bookinfo.tsx
  client/src/routers/routers.tsx
  client/src/schemas/books.schema.ts
  server/src/entities/books.entity.ts
  server/src/resolvers/books.resolver.ts
  server/src/services/migration/books.migration.ts
Labels: Conflict Resolved, Lead Review

#129 feat(071-ft): add book section
  client/src/pages/books/BooksPage.css
  client/src/pages/books/BooksPage.tsx
Labels: Lead Review
